/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.BacSiDAO;
import com.edusys.dao.BenhAnDAO;
import com.edusys.dao.DichVuDAO;
import com.edusys.dao.KhoaDAO;
import com.edusys.entity.BacSi;
import com.edusys.entity.BenhAn;
import com.edusys.entity.DichVu;
import com.edusys.entity.Hoadon;
import com.edusys.entity.Hoadonchitiet;
import com.edusys.entity.Khoa;
import com.edusys.entity.Thuoc;
import com.edusys.utils.MsgBox;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anime
 */
public class ThongkeBacSiJDialog extends javax.swing.JDialog {
     DichVuDAO daodichvu = new DichVuDAO();
     BacSiDAO bacsidao = new BacSiDAO();
     KhoaDAO Khoadao = new KhoaDAO();
     BenhAnDAO benhandao = new BenhAnDAO();
     
     int row = 0;

    /**
     * Creates new form ThongkeJDialog
     */
    public ThongkeBacSiJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FillTabledichvu();
        FillTablebacsi();
        FillTableKhoa();
        FillTablebenhan();
        setLocationRelativeTo(null); 
    }
    
    
    
    
    
        void FillTabledichvu() {
        DefaultTableModel model = (DefaultTableModel) tblbacsi1.getModel();
        model.setRowCount(0);
        try {
            List<DichVu> list = daodichvu.selectAll();
            for (DichVu nv : list) {
                Object[] row = {
                    nv.getMã_Dịch_Vụ(),
                    nv.getXét_Nghiệm(),
                    nv.getMã_Bệnh_Án()
                };
                model.addRow(row);  // Thêm hàng vào mô hình bảng
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn Lỗi Dữ Liệu");
        }
    }
            
            
            
        void FillTablebacsi() {
        DefaultTableModel model = (DefaultTableModel) tblbacsi.getModel();
        model.setRowCount(0);
        try {
            List<BacSi> list = bacsidao.selectAll();
            for (BacSi nv : list) {
                Object[] row = {
                    nv.getID_Bác_Sĩ(),
                    nv.getHọ(),
                    nv.getTên(),
                    nv.getĐịa_Chỉ(),
                    nv.getSố_Điện_Thoại(),
                    nv.getMã_khoa(),
                    nv.getChuyên_Môn(),
                    nv.getChức_Vụ(),
                    nv.getMã_Bệnh_Án()
                };
                model.addRow(row);  // Thêm hàng vào mô hình bảng
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn Lỗi Dữ Liệu");
        }
    }
            
            
            
    void FillTableKhoa() {
    DefaultTableModel model = (DefaultTableModel) tblkhoa.getModel();
    model.setRowCount(0);
    try {
        List <Khoa> list = Khoadao.selectAll();
        for (Khoa BA : list) {
            Object[] row = {
                BA.getMã_Khoa(),
                BA.getTên_Khoa(),
                BA.getTrưởng_Khoa(),
                BA.getID_Bác_Sĩ(),
            };
            model.addRow(row);  // Thêm hàng vào mô hình bảng
        }
    } catch (Exception e) {
        MsgBox.alert(this, "Lỗi Truy Vấn Lỗi Dữ Liệu");
    }
}  
            
    void FillTablebenhan() {
    DefaultTableModel model = (DefaultTableModel) tblBenhAn.getModel();
    model.setRowCount(0);
    try {
        List <BenhAn> list = benhandao.selectAll();
        for (BenhAn BA : list) {
            Object[] row = {
                BA.getMã_Bệnh_Án(),
                BA.getBệnh_dự_đoán(),
                BA.getTriệu_chứng(),
                BA.getChẩn_Đoán(),
                BA.getPhương_Pháp(),
            };
            model.addRow(row);  // Thêm hàng vào mô hình bảng
        }
    } catch (Exception e) {
        MsgBox.alert(this, "Lỗi Truy Vấn Lỗi Dữ Liệu");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbacsi1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblbacsi = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblkhoa = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBenhAn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblbacsi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Dịch Vụ", "Xét Nghiệm", "Mã Bệnh Án"
            }
        ));
        tblbacsi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbacsi1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblbacsi1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblbacsi1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabs.addTab("Dịch vụ", jPanel4);

        tblbacsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Bác_Sĩ", "Họ", "Tên", "Địa_Chỉ", "Số_Điện_Thoại", "Mã_khoa", "Chuyên_Môn", "Chức_Vụ", "Mã_Bệnh_Án"
            }
        ));
        tblbacsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbacsiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblbacsiMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tblbacsi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabs.addTab("Bác Sĩ", jPanel2);

        tblkhoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã_Khoa", "Tên_Khoa", "Trưởng_Khoa", "ID_Bác_Sĩ"
            }
        ));
        tblkhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblkhoaMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblkhoa);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabs.addTab("Khoa", jPanel5);

        tblBenhAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã_Bệnh_Án", "Bệnh_dự_đoán", "Triệu_chứng", "Chẩn_Đoán", "Phương_Pháp"
            }
        ));
        tblBenhAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBenhAnMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblBenhAn);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabs.addTab("Bệnh Án", jPanel6);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText(" Thông Kê Bác Sĩ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBenhAnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBenhAnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBenhAnMousePressed

    private void tblkhoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhoaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblkhoaMousePressed

    private void tblbacsiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbacsiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbacsiMousePressed

    private void tblbacsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbacsiMouseClicked
        // TODO add your handling code here:x
    }//GEN-LAST:event_tblbacsiMouseClicked

    private void tblbacsi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbacsi1MouseClicked
        // TODO add your handling code here:x
    }//GEN-LAST:event_tblbacsi1MouseClicked

    private void tblbacsi1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbacsi1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblbacsi1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongkeBacSiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongkeBacSiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongkeBacSiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongkeBacSiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongkeBacSiJDialog dialog = new ThongkeBacSiJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblBenhAn;
    private javax.swing.JTable tblbacsi;
    private javax.swing.JTable tblbacsi1;
    private javax.swing.JTable tblkhoa;
    // End of variables declaration//GEN-END:variables
}
