/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class Trangchu2JFrame extends javax.swing.JFrame {
    void init(){
         setSize(1000, 600);
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("Hệ Thống Quản Lý Bệnh Nhân");
        new Timer(1000, new ActionListener(){
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
            @Override
            public void actionPerformed(ActionEvent e) {
                lbldongho.setText(format.format(new Date()));
            }
            
        }).start();
    }

    /**
     * Creates new form Trangchu2JFrame
     */
    public Trangchu2JFrame() {
        initComponents();
        init();
    }
    void openDoiMatKhau(){
            new DoiMatKhauJDialog(this, true).setVisible(true);     
    }
    void dangxuat(){
        Auth.clear();
        new DangNhapJDialog(this, true).setVisible(true);
    }
    void ketthuc(){
        if (MsgBox.confirm(this, "Bạn muốn kêt thúc làm việc")) {
            System.exit(0);
        }
    }
    void trunggian(){
        new trungGianJDialog(this, true).setVisible(true);
        dispose();
    }
    void dichvu(){
        new DichVuJDialog(this, true).setVisible(true);
    }
    void hoadon(){
        new HoadonJDialog(this, true).setVisible(true);
        dispose();
    }
    void benhnhan(){
        new BenhnhanJDialog1(this, true).setVisible(true);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btndangxuat = new javax.swing.JButton();
        btnkethuc = new javax.swing.JButton();
        btnbacsi = new javax.swing.JButton();
        btnbenhnhan = new javax.swing.JButton();
        btnhoadon = new javax.swing.JButton();
        btndichvu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbldongho = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuhethong = new javax.swing.JMenu();
        menuitemDoiMK = new javax.swing.JMenuItem();
        menuitemdangxuat = new javax.swing.JMenuItem();
        menuitemkethuc = new javax.swing.JMenuItem();
        menuquanly = new javax.swing.JMenu();
        menuitemchuyende = new javax.swing.JMenuItem();
        menuitemkhoahoc = new javax.swing.JMenuItem();
        menuitemnguoihoc = new javax.swing.JMenuItem();
        menuitemnhanvien = new javax.swing.JMenuItem();
        menutrogiup = new javax.swing.JMenu();
        menuitemHDSD = new javax.swing.JMenuItem();
        menuitemGTSP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Log out.png"))); // NOI18N
        btndangxuat.setText("Đăng xuất");
        btndangxuat.setFocusable(false);
        btndangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btndangxuat);

        btnkethuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Stop.png"))); // NOI18N
        btnkethuc.setText("Kết Thúc");
        btnkethuc.setFocusable(false);
        btnkethuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkethuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkethuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkethucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkethuc);

        btnbacsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/User.png"))); // NOI18N
        btnbacsi.setText("Bác Sĩ");
        btnbacsi.setFocusable(false);
        btnbacsi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbacsi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbacsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacsiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbacsi);

        btnbenhnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Boy.png"))); // NOI18N
        btnbenhnhan.setText("Bệnh Nhân");
        btnbenhnhan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbenhnhan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbenhnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbenhnhanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbenhnhan);

        btnhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Lists.png"))); // NOI18N
        btnhoadon.setText("Hóa Đơn");
        btnhoadon.setFocusable(false);
        btnhoadon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhoadon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhoadonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhoadon);

        btndichvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Clien list.png"))); // NOI18N
        btndichvu.setText("Dịch Vụ");
        btndichvu.setFocusable(false);
        btndichvu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndichvu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndichvuActionPerformed(evt);
            }
        });
        jToolBar1.add(btndichvu);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Alarm.png"))); // NOI18N
        lbldongho.setText("12:12:12 AM");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Info.png"))); // NOI18N
        jLabel2.setText("Hệ Thống Quản Lý Đào Tạo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldongho)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbldongho))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        menuhethong.setText("Hệ thống");

        menuitemDoiMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/Refresh.png"))); // NOI18N
        menuitemDoiMK.setText("Đổi mật khẩu");
        menuitemDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDoiMKActionPerformed(evt);
            }
        });
        menuhethong.add(menuitemDoiMK);

        menuitemdangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemdangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/Exit button.png"))); // NOI18N
        menuitemdangxuat.setText("Đăng xuất");
        menuitemdangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemdangxuatActionPerformed(evt);
            }
        });
        menuhethong.add(menuitemdangxuat);

        menuitemkethuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuitemkethuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/Closed door.png"))); // NOI18N
        menuitemkethuc.setText("Kết thúc");
        menuitemkethuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemkethucActionPerformed(evt);
            }
        });
        menuhethong.add(menuitemkethuc);

        jMenuBar1.add(menuhethong);

        menuquanly.setText("Quản lý");

        menuitemchuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/User.png"))); // NOI18N
        menuitemchuyende.setText("Bác Sĩ");
        menuitemchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemchuyendeActionPerformed(evt);
            }
        });
        menuquanly.add(menuitemchuyende);

        menuitemkhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/Boy.png"))); // NOI18N
        menuitemkhoahoc.setText("Bệnh Nhân");
        menuitemkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemkhoahocActionPerformed(evt);
            }
        });
        menuquanly.add(menuitemkhoahoc);

        menuitemnguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/Lists.png"))); // NOI18N
        menuitemnguoihoc.setText("Hóa Đơn");
        menuitemnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemnguoihocActionPerformed(evt);
            }
        });
        menuquanly.add(menuitemnguoihoc);

        menuitemnhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Duan1/icon/Clien list.png"))); // NOI18N
        menuitemnhanvien.setText("Dịch Vụ");
        menuitemnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemnhanvienActionPerformed(evt);
            }
        });
        menuquanly.add(menuitemnhanvien);

        jMenuBar1.add(menuquanly);

        menutrogiup.setText("Trợ giúp");

        menuitemHDSD.setText("Hướng dẫn sử dụng");
        menutrogiup.add(menuitemHDSD);

        menuitemGTSP.setText("Giới thiệu sản phẩm");
        menutrogiup.add(menuitemGTSP);

        jMenuBar1.add(menutrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        // TODO add your handling code here:
        dangxuat();
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btnkethucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkethucActionPerformed
        // TODO add your handling code here:
        ketthuc();
    }//GEN-LAST:event_btnkethucActionPerformed

    private void btnbacsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacsiActionPerformed
        // TODO add your handling code here:
        trunggian();
    }//GEN-LAST:event_btnbacsiActionPerformed

    private void btnbenhnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbenhnhanActionPerformed
        // TODO add your handling code here:
        benhnhan();
    }//GEN-LAST:event_btnbenhnhanActionPerformed

    private void btnhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhoadonActionPerformed
        // TODO add your handling code here:
        hoadon();
    }//GEN-LAST:event_btnhoadonActionPerformed

    private void btndichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndichvuActionPerformed
        // TODO add your handling code here:
        dichvu();
    }//GEN-LAST:event_btndichvuActionPerformed

    private void menuitemDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDoiMKActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_menuitemDoiMKActionPerformed

    private void menuitemdangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemdangxuatActionPerformed
        // TODO add your handling code here:
        dangxuat();
    }//GEN-LAST:event_menuitemdangxuatActionPerformed

    private void menuitemkethucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemkethucActionPerformed
        // TODO add your handling code here:
        ketthuc();
    }//GEN-LAST:event_menuitemkethucActionPerformed

    private void menuitemchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemchuyendeActionPerformed
        // TODO add your handling code here:
        trunggian();
    }//GEN-LAST:event_menuitemchuyendeActionPerformed

    private void menuitemkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemkhoahocActionPerformed
        // TODO add your handling code here:
        benhnhan();
    }//GEN-LAST:event_menuitemkhoahocActionPerformed

    private void menuitemnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemnguoihocActionPerformed
        // TODO add your handling code here:
        hoadon();
    }//GEN-LAST:event_menuitemnguoihocActionPerformed

    private void menuitemnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemnhanvienActionPerformed
        // TODO add your handling code here:
        dichvu();
    }//GEN-LAST:event_menuitemnhanvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trangchu2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trangchu2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trangchu2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trangchu2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trangchu2JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbacsi;
    private javax.swing.JButton btnbenhnhan;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btndichvu;
    private javax.swing.JButton btnhoadon;
    private javax.swing.JButton btnkethuc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenu menuhethong;
    private javax.swing.JMenuItem menuitemDoiMK;
    private javax.swing.JMenuItem menuitemGTSP;
    private javax.swing.JMenuItem menuitemHDSD;
    private javax.swing.JMenuItem menuitemchuyende;
    private javax.swing.JMenuItem menuitemdangxuat;
    private javax.swing.JMenuItem menuitemkethuc;
    private javax.swing.JMenuItem menuitemkhoahoc;
    private javax.swing.JMenuItem menuitemnguoihoc;
    private javax.swing.JMenuItem menuitemnhanvien;
    private javax.swing.JMenu menuquanly;
    private javax.swing.JMenu menutrogiup;
    // End of variables declaration//GEN-END:variables
}
